articulo = int(input("ingrese el precio de su articulo: "))
descuento = int(articulo*0.15)
total = int(articulo-descuento)
print ("El descuento de su producto es: ", descuento)
print("El valor total es: ", total)
